//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.29 at 10:59:52 PM EEST 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.spring.guides.gs_producing_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetMaxMQuantsIdResponce }
     * 
     */
    public GetMaxMQuantsIdResponce createGetMaxMQuantsIdResponce() {
        return new GetMaxMQuantsIdResponce();
    }

    /**
     * Create an instance of {@link GetMaxMQuantsIdRequest }
     * 
     */
    public GetMaxMQuantsIdRequest createGetMaxMQuantsIdRequest() {
        return new GetMaxMQuantsIdRequest();
    }

    /**
     * Create an instance of {@link GetMQuantInfoByIdRequest }
     * 
     */
    public GetMQuantInfoByIdRequest createGetMQuantInfoByIdRequest() {
        return new GetMQuantInfoByIdRequest();
    }

    /**
     * Create an instance of {@link GetTypeMQListRequest }
     * 
     */
    public GetTypeMQListRequest createGetTypeMQListRequest() {
        return new GetTypeMQListRequest();
    }

    /**
     * Create an instance of {@link GetMQuantInfoResponce }
     * 
     */
    public GetMQuantInfoResponce createGetMQuantInfoResponce() {
        return new GetMQuantInfoResponce();
    }

    /**
     * Create an instance of {@link MeasQuants }
     * 
     */
    public MeasQuants createMeasQuants() {
        return new MeasQuants();
    }

    /**
     * Create an instance of {@link GetTypeMQListResponce }
     * 
     */
    public GetTypeMQListResponce createGetTypeMQListResponce() {
        return new GetTypeMQListResponce();
    }

    /**
     * Create an instance of {@link TypeMq }
     * 
     */
    public TypeMq createTypeMq() {
        return new TypeMq();
    }

    /**
     * Create an instance of {@link GetMQuantInfoRequest }
     * 
     */
    public GetMQuantInfoRequest createGetMQuantInfoRequest() {
        return new GetMQuantInfoRequest();
    }

    /**
     * Create an instance of {@link GetMQuantInfoByIdResponce }
     * 
     */
    public GetMQuantInfoByIdResponce createGetMQuantInfoByIdResponce() {
        return new GetMQuantInfoByIdResponce();
    }

}
